[Settings]
; Num 9
AscendKey=105
; Num 8
DescendKey=104
AscendSpeed=1.5
DescendSpeed=-1.5

; Apply to player only (1) or to everyone in the world (0 - fun mode!)
; Note: PlayerOnly requires a valid pointer. If 0, everyone flies when you press the key.
PlayerOnly=0
